#include <sge/opencl/image_format_output.hpp>
#include <ostream>

#define SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(constant) case constant: s << #constant; break

void
sge::opencl::image_format_output(
	std::ostream &s,
	cl_image_format const &_if)
{
	switch(_if.image_channel_order)
	{
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_R);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_A);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_INTENSITY);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_LUMINANCE);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_RG);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_RA);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_RGB);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_RGBA);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_ARGB);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_BGRA);
	}

	s << " ";

	switch(_if.image_channel_data_type)
	{
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_SNORM_INT8);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_SNORM_INT16);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNORM_INT8);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNORM_INT16);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNORM_SHORT_565);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNORM_SHORT_555);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNORM_INT_101010);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_SIGNED_INT8);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_SIGNED_INT16);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_SIGNED_INT32);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNSIGNED_INT8);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNSIGNED_INT16);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_UNSIGNED_INT32);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_HALF_FLOAT);
		SGE_OPENCL_IMAGE_FORMAT_OUTPUT_HELPER(
			CL_FLOAT);
	}
}
