#!/bin/sh

username="phillemann"

echo "executing doxygen"

doxygen || exit "doxygen failed!"

echo "switching to doc directory; compressing documentation"

cd doc;

tar cjf /tmp/doc_archive.tar.bz2 html || exit "couldn't compress"

echo "connecting to server, uploading documentation"

scp /tmp/doc_archive.tar.bz2 $username@ssh.tuxfamily.org:~/ || exit "couldn't upload documentation"

echo "deleting old documentation, unpacking new"

#ssh $username@ssh.tuxfamily.org 'rm -r /home/sge/*/htdocs/html; tar xjf /home/sge/*/htdocs/doc_archive.tar.bz2 -C /home/sge/*/htdocs/; rm /home/sge/*/htdocs/doc_archive.tar.bz2' 
ssh $username@ssh.tuxfamily.org '/home/unpack_script' 
