#ifndef SGE_AUDIO_AUDIO_HPP_INCLUDED
#define SGE_AUDIO_AUDIO_HPP_INCLUDED

#include <sge/audio/angle.hpp>
#include <sge/audio/angle_fwd.hpp>
#include <sge/audio/bad_sound_alloc.hpp>
#include <sge/audio/buffer.hpp>
#include <sge/audio/buffer_fwd.hpp>
#include <sge/audio/buffer_ptr.hpp>
#include <sge/audio/channel_type.hpp>
#include <sge/audio/exception.hpp>
#include <sge/audio/exception_fwd.hpp>
#include <sge/audio/file.hpp>
#include <sge/audio/file_exception.hpp>
#include <sge/audio/file_fwd.hpp>
#include <sge/audio/file_ptr.hpp>
#include <sge/audio/listener.hpp>
#include <sge/audio/listener_fwd.hpp>
#include <sge/audio/loader.hpp>
#include <sge/audio/loader_capabilities.hpp>
#include <sge/audio/loader_capabilities_field.hpp>
#include <sge/audio/loader_fwd.hpp>
#include <sge/audio/loader_plugin.hpp>
#include <sge/audio/loader_ptr.hpp>
#include <sge/audio/multi_loader.hpp>
#include <sge/audio/multi_loader_fwd.hpp>
#include <sge/audio/optional_path.hpp>
#include <sge/audio/player.hpp>
#include <sge/audio/player_capabilities.hpp>
#include <sge/audio/player_capabilities_field.hpp>
#include <sge/audio/player_fwd.hpp>
#include <sge/audio/player_plugin.hpp>
#include <sge/audio/player_ptr.hpp>
#include <sge/audio/pool.hpp>
#include <sge/audio/pool_fwd.hpp>
#include <sge/audio/sample_container.hpp>
#include <sge/audio/sample_count.hpp>
#include <sge/audio/scalar.hpp>
#include <sge/audio/sound/sound.hpp>
#include <sge/audio/stop_mode.hpp>
#include <sge/audio/unsupported_format.hpp>
#include <sge/audio/vector.hpp>

#endif
