#ifndef SGE_RENDERER_VF_VF_HPP_INCLUDED
#define SGE_RENDERER_VF_VF_HPP_INCLUDED

#include <sge/renderer/vf/color.hpp>
#include <sge/renderer/vf/color_base.hpp>
#include <sge/renderer/vf/const_tag.hpp>
#include <sge/renderer/vf/dynamic/dynamic.hpp>
#include <sge/renderer/vf/element_type.hpp>
#include <sge/renderer/vf/format.hpp>
#include <sge/renderer/vf/format_fwd.hpp>
#include <sge/renderer/vf/index.hpp>
#include <sge/renderer/vf/index_fwd.hpp>
#include <sge/renderer/vf/is_index.hpp>
#include <sge/renderer/vf/iterator.hpp>
#include <sge/renderer/vf/iterator_decl.hpp>
#include <sge/renderer/vf/iterator_fwd.hpp>
#include <sge/renderer/vf/iterator_impl.hpp>
#include <sge/renderer/vf/make_unspecified_tag.hpp>
#include <sge/renderer/vf/nonconst_tag.hpp>
#include <sge/renderer/vf/normal.hpp>
#include <sge/renderer/vf/part.hpp>
#include <sge/renderer/vf/part_fwd.hpp>
#include <sge/renderer/vf/pointer.hpp>
#include <sge/renderer/vf/pos.hpp>
#include <sge/renderer/vf/single_base.hpp>
#include <sge/renderer/vf/string.hpp>
#include <sge/renderer/vf/texpos.hpp>
#include <sge/renderer/vf/texpos_fwd.hpp>
#include <sge/renderer/vf/unspecified.hpp>
#include <sge/renderer/vf/unspecified_base.hpp>
#include <sge/renderer/vf/unspecified_tag.hpp>
#include <sge/renderer/vf/vector.hpp>
#include <sge/renderer/vf/vector3_base.hpp>
#include <sge/renderer/vf/vector_base.hpp>
#include <sge/renderer/vf/vector_fwd.hpp>
#include <sge/renderer/vf/vertex.hpp>
#include <sge/renderer/vf/vertex_decl.hpp>
#include <sge/renderer/vf/vertex_difference.hpp>
#include <sge/renderer/vf/vertex_fwd.hpp>
#include <sge/renderer/vf/vertex_impl.hpp>
#include <sge/renderer/vf/vertex_size.hpp>
#include <sge/renderer/vf/view.hpp>
#include <sge/renderer/vf/view_decl.hpp>
#include <sge/renderer/vf/view_fwd.hpp>
#include <sge/renderer/vf/view_impl.hpp>

#endif
