#include <sge/collision/shapes/base.hpp>
#include <sge/collision/shapes/base_fwd.hpp>
#include <sge/collision/shapes/base_ptr.hpp>
#include <sge/collision/shapes/box.hpp>
#include <sge/collision/shapes/box_fwd.hpp>
#include <sge/collision/shapes/box_ptr.hpp>
#include <sge/collision/shapes/container.hpp>
#include <sge/collision/shapes/shapes.hpp>
#include <sge/collision/shapes/sphere.hpp>
#include <sge/collision/shapes/sphere_fwd.hpp>
#include <sge/collision/shapes/sphere_ptr.hpp>
