#ifndef SGE_INPUT_KEYBOARD_KEYBOARD_HPP_INCLUDED
#define SGE_INPUT_KEYBOARD_KEYBOARD_HPP_INCLUDED

#include <sge/input/keyboard/action.hpp>
#include <sge/input/keyboard/char_callback.hpp>
#include <sge/input/keyboard/char_event.hpp>
#include <sge/input/keyboard/char_event_fwd.hpp>
#include <sge/input/keyboard/char_function.hpp>
#include <sge/input/keyboard/char_type.hpp>
#include <sge/input/keyboard/collector.hpp>
#include <sge/input/keyboard/collector_fwd.hpp>
#include <sge/input/keyboard/device.hpp>
#include <sge/input/keyboard/device_fwd.hpp>
#include <sge/input/keyboard/device_ptr.hpp>
#include <sge/input/keyboard/device_vector.hpp>
#include <sge/input/keyboard/digit.hpp>
#include <sge/input/keyboard/discover_callback.hpp>
#include <sge/input/keyboard/discover_function.hpp>
#include <sge/input/keyboard/discover_signal.hpp>
#include <sge/input/keyboard/is_alt.hpp>
#include <sge/input/keyboard/is_ctrl.hpp>
#include <sge/input/keyboard/is_shift.hpp>
#include <sge/input/keyboard/key_callback.hpp>
#include <sge/input/keyboard/key_code.hpp>
#include <sge/input/keyboard/key_code_to_digit.hpp>
#include <sge/input/keyboard/key_event.hpp>
#include <sge/input/keyboard/key_event_fwd.hpp>
#include <sge/input/keyboard/key_function.hpp>
#include <sge/input/keyboard/key_repeat_callback.hpp>
#include <sge/input/keyboard/key_repeat_event.hpp>
#include <sge/input/keyboard/key_repeat_event_fwd.hpp>
#include <sge/input/keyboard/key_repeat_function.hpp>
#include <sge/input/keyboard/mod_state.hpp>
#include <sge/input/keyboard/modifier.hpp>
#include <sge/input/keyboard/optional_digit.hpp>
#include <sge/input/keyboard/optional_modifier.hpp>
#include <sge/input/keyboard/remove_callback.hpp>
#include <sge/input/keyboard/remove_function.hpp>
#include <sge/input/keyboard/remove_signal.hpp>
#include <sge/input/keyboard/to_modifier.hpp>

#endif
