from glob import glob

workdir = ARGUMENTS.get('workdir', '')
prefix = ARGUMENTS.get('prefix', '.')
libdir = ARGUMENTS.get('libdir', 'lib')

flags = '-Wall -ansi -pedantic -O3'
lib_path = workdir + prefix + '/' + libdir
plugin_path = lib_path + '/spacegame'
bin_path = workdir + prefix + '/bin'
media_path = prefix + '/share/games/spacegame'

core = Environment(LIBS = ['boost_filesystem', 'boost_signals', 'X11', 'dl'], CCFLAGS = flags, CPPDEFINES = {'PLUGIN_PATH':"\\\"" + prefix + '/' + libdir + '/spacegame' + "\\\"", 'MEDIA_PATH':"\\\"" + media_path + "\\\""})
libcore = core.SharedLibrary('sgecore', [glob('./core/main/src/*.cpp'), glob('./core/math/src/*.cpp'), glob('./core/renderer/src/*.cpp'), glob('./core/sprite/src/*.cpp')])

gui = Environment(LIBPATH = ['.'], LIBS = ['boost_filesystem', 'boost_signals', 'sgecore'], CCFLAGS = flags)
libgui = gui.SharedLibrary('sgegui', [glob('./gui/src/*.cpp')])

ogl = Environment(LIBS = ['GL', 'X11', 'GLEW', 'Xxf86vm'], CCFLAGS = flags)
libogl = ogl.SharedLibrary('sgeogl', [glob('./plugins/ogl/src/*.cpp')])

devil = Environment(LIBS = ['IL', 'ILU'], CCFLAGS = flags)
libdevil = devil.SharedLibrary('sgedevil', [glob('./plugins/devil/src/*.cpp')])

freetype = Environment(LIBS = ['freetype'], CCFLAGS = flags)
freetype.Append(CCFLAGS = ' -I/usr/include/freetype2')
libfreetype = freetype.SharedLibrary('sgefreetype', [glob('./plugins/freetype/src/*.cpp')])

xinput = Environment(LIBS = ['X11', 'Xxf86dga'], CCFLAGS = flags)
libxinput = xinput.SharedLibrary('sgexinput', [glob('./plugins/xinput/src/*.cpp')])

#d3d = Environment(LIBS = ['winelib'], CCFLAGS = flags)
#libd3d = d3d.SharedLibrary('sged3d', [glob('./plugins/d3d/src/*.cpp')])

test = Environment(LIBPATH = ['.'], LIBS = ['sgecore','sgegui'], CCFLAGS = flags)
testapp = test.Program('sgetest', ['./test/test.cpp'])

installer = Environment()
installer.Alias(target = "install", source = [core.Install(lib_path,libcore), gui.Install(lib_path,libgui), ogl.Install(plugin_path,libogl), devil.Install(plugin_path,libdevil), freetype.Install(plugin_path,libfreetype), xinput.Install(plugin_path,libxinput), test.Install(bin_path,testapp)])
