#ifndef SGE_SPRITE_SPRITE_HPP_INCLUDED
#define SGE_SPRITE_SPRITE_HPP_INCLUDED

#include <sge/sprite/animation/animation.hpp>
#include <sge/sprite/bounding_rect.hpp>
#include <sge/sprite/center.hpp>
#include <sge/sprite/choices.hpp>
#include <sge/sprite/color.hpp>
#include <sge/sprite/compare_depth.hpp>
#include <sge/sprite/default_compare.hpp>
#include <sge/sprite/default_equal.hpp>
#include <sge/sprite/default_parameters.hpp>
#include <sge/sprite/default_sort.hpp>
#include <sge/sprite/defaults.hpp>
#include <sge/sprite/defaults/defaults.hpp>
#include <sge/sprite/depth_type.hpp>
#include <sge/sprite/dim.hpp>
#include <sge/sprite/dont_sort.hpp>
#include <sge/sprite/external_system_decl.hpp>
#include <sge/sprite/external_system_fwd.hpp>
#include <sge/sprite/external_system_impl.hpp>
#include <sge/sprite/intrusive/intrusive.hpp>
#include <sge/sprite/matrix.hpp>
#include <sge/sprite/no_color.hpp>
#include <sge/sprite/object.hpp>
#include <sge/sprite/object_decl.hpp>
#include <sge/sprite/object_fwd.hpp>
#include <sge/sprite/object_impl.hpp>
#include <sge/sprite/parameters.hpp>
#include <sge/sprite/parameters_decl.hpp>
#include <sge/sprite/parameters_fwd.hpp>
#include <sge/sprite/parameters_impl.hpp>
#include <sge/sprite/point_size.hpp>
#include <sge/sprite/primitives/primitives.hpp>
#include <sge/sprite/projection_matrix.hpp>
#include <sge/sprite/rect.hpp>
#include <sge/sprite/render_one.hpp>
#include <sge/sprite/render_one_advanced.hpp>
#include <sge/sprite/render_states.hpp>
#include <sge/sprite/repetition_type.hpp>
#include <sge/sprite/roles/roles.hpp>
#include <sge/sprite/rotation_type.hpp>
#include <sge/sprite/set_matrices.hpp>
#include <sge/sprite/symbol.hpp>
#include <sge/sprite/system.hpp>
#include <sge/sprite/system_base_decl.hpp>
#include <sge/sprite/system_base_fwd.hpp>
#include <sge/sprite/system_base_impl.hpp>
#include <sge/sprite/texture_coordinates.hpp>
#include <sge/sprite/texture_dim.hpp>
#include <sge/sprite/type_choices.hpp>
#include <sge/sprite/unspecified_dim_tag.hpp>
#include <sge/sprite/vector.hpp>
#include <sge/sprite/with_color.hpp>
#include <sge/sprite/with_depth.hpp>
#include <sge/sprite/with_dim.hpp>
#include <sge/sprite/with_repetition.hpp>
#include <sge/sprite/with_rotation.hpp>
#include <sge/sprite/with_rotation_center.hpp>
#include <sge/sprite/with_texture.hpp>
#include <sge/sprite/with_texture_coordinates.hpp>
#include <sge/sprite/with_unspecified_dim.hpp>
#include <sge/sprite/with_visibility.hpp>

#endif
