#ifndef SGE_COLLISION_COLLISION_HPP_INCLUDED
#define SGE_COLLISION_COLLISION_HPP_INCLUDED

#include <sge/collision/body.hpp>
#include <sge/collision/body_fwd.hpp>
#include <sge/collision/body_ptr.hpp>
#include <sge/collision/box.hpp>
#include <sge/collision/callback.hpp>
#include <sge/collision/callback_fn.hpp>
#include <sge/collision/callback_signal.hpp>
#include <sge/collision/collision.hpp>
#include <sge/collision/const_satellite_ptr.hpp>
#include <sge/collision/constraint.hpp>
#include <sge/collision/dim.hpp>
#include <sge/collision/group.hpp>
#include <sge/collision/group_fwd.hpp>
#include <sge/collision/group_overflow.hpp>
#include <sge/collision/group_ptr.hpp>
#include <sge/collision/optional_box.hpp>
#include <sge/collision/plugin.hpp>
#include <sge/collision/point.hpp>
#include <sge/collision/satellite.hpp>
#include <sge/collision/satellite_fwd.hpp>
#include <sge/collision/satellite_ptr.hpp>
#include <sge/collision/shape_ambiguity.hpp>
#include <sge/collision/shape_callback.hpp>
#include <sge/collision/shape_callback_fn.hpp>
#include <sge/collision/shapes/shapes.hpp>
#include <sge/collision/solidity.hpp>
#include <sge/collision/system.hpp>
#include <sge/collision/system_fwd.hpp>
#include <sge/collision/system_ptr.hpp>
#include <sge/collision/test_callback.hpp>
#include <sge/collision/test_callback_combiner.hpp>
#include <sge/collision/test_callback_fn.hpp>
#include <sge/collision/time_unit.hpp>
#include <sge/collision/unit.hpp>
#include <sge/collision/world.hpp>
#include <sge/collision/world_fwd.hpp>
#include <sge/collision/world_ptr.hpp>

#endif
