#include <sge/sprite/primitives/adder.hpp>
#include <sge/sprite/primitives/bool.hpp>
#include <sge/sprite/primitives/color.hpp>
#include <sge/sprite/primitives/coordinates.hpp>
#include <sge/sprite/primitives/dim.hpp>
#include <sge/sprite/primitives/float.hpp>
#include <sge/sprite/primitives/order.hpp>
#include <sge/sprite/primitives/point_size.hpp>
#include <sge/sprite/primitives/primitives.hpp>
#include <sge/sprite/primitives/texture.hpp>
#include <sge/sprite/primitives/vector.hpp>
