#include <sge/image/color/alpha8.hpp>
#include <sge/image/color/alpha8_format.hpp>
#include <sge/image/color/any/any.hpp>
#include <sge/image/color/argb32f.hpp>
#include <sge/image/color/argb32f_format.hpp>
#include <sge/image/color/argb8.hpp>
#include <sge/image/color/argb8_format.hpp>
#include <sge/image/color/bgra32f.hpp>
#include <sge/image/color/bgra32f_format.hpp>
#include <sge/image/color/bgra8.hpp>
#include <sge/image/color/bgra8_format.hpp>
#include <sge/image/color/channel32f.hpp>
#include <sge/image/color/channel8.hpp>
#include <sge/image/color/color.hpp>
#include <sge/image/color/convert.hpp>
#include <sge/image/color/element_count.hpp>
#include <sge/image/color/elements.hpp>
#include <sge/image/color/format.hpp>
#include <sge/image/color/format_static.hpp>
#include <sge/image/color/format_stride.hpp>
#include <sge/image/color/format_to_string.hpp>
#include <sge/image/color/gray8.hpp>
#include <sge/image/color/gray8_format.hpp>
#include <sge/image/color/init.hpp>
#include <sge/image/color/object.hpp>
#include <sge/image/color/object_impl.hpp>
#include <sge/image/color/print.hpp>
#include <sge/image/color/rgb32f.hpp>
#include <sge/image/color/rgb32f_format.hpp>
#include <sge/image/color/rgb8.hpp>
#include <sge/image/color/rgb8_format.hpp>
#include <sge/image/color/rgba32f.hpp>
#include <sge/image/color/rgba32f_format.hpp>
#include <sge/image/color/rgba8.hpp>
#include <sge/image/color/rgba8_format.hpp>
