#include <sge/sprite/roles/adder.hpp>
#include <sge/sprite/roles/color.hpp>
#include <sge/sprite/roles/depth.hpp>
#include <sge/sprite/roles/order.hpp>
#include <sge/sprite/roles/point_size.hpp>
#include <sge/sprite/roles/pos.hpp>
#include <sge/sprite/roles/repetition.hpp>
#include <sge/sprite/roles/roles.hpp>
#include <sge/sprite/roles/rotate_around.hpp>
#include <sge/sprite/roles/rotation.hpp>
#include <sge/sprite/roles/size.hpp>
#include <sge/sprite/roles/texture.hpp>
#include <sge/sprite/roles/texture_coordinates.hpp>
#include <sge/sprite/roles/use_rotation.hpp>
#include <sge/sprite/roles/visible.hpp>
