#include <sge/camera/activation_state.hpp>
#include <sge/camera/camera.hpp>
#include <sge/camera/gizmo/gizmo.hpp>
#include <sge/camera/gizmo_type.hpp>
#include <sge/camera/identity_gizmo.hpp>
#include <sge/camera/object.hpp>
#include <sge/camera/object_fwd.hpp>
#include <sge/camera/parameters.hpp>
#include <sge/camera/parameters_fwd.hpp>
#include <sge/camera/projection/projection.hpp>
#include <sge/camera/symbol.hpp>
